name: GitHub Pages Build
on:
  push:
    branches: [ jekyll ]
  pull_request:
    branches: [ jekyll ]
  schedule:
    - cron:  '0 */24 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Install NPM ⬇️
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM Packages 🔧
        run: npm install
        env:
          CI: true
      - name: Build & Deploy 🚀
        uses: meitar/jekyll-builder-for-github-pages-action@builder-3.8
        env:
          PAGES_REPO_NWO: ${{ github.repository }}
          JEKYLL_GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          SECRET_GH_PAGES_API_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          POST_BUILD_COMMANDS: |
            cp CNAME $JEKYLL_DATA_DIR
            cp -R .well-known $JEKYLL_DATA_DIR
          GIT_COMMIT_MESSAGE: Auto-commit from GitHub Actions Jekyll Builder.
